<?php
/**
 * Created by JetBrains PhpStorm.
 * User: sidler
 * Date: 12.08.13
 * Time: 09:33
 * To change this template use File | Settings | File Templates.
 */

class CssMapper implements IDataMapper {

    private $strSpriteName = "";

    private $strOutputBuffer = "";
    private $strOutName = "sprite.css";
    private $strOutputDir = "";

    /**
     * @param $strOutputDir
     *
     * @return mixed
     */
    public function setStrOutputDir($strOutputDir) {
        $this->strOutputDir = $strOutputDir;
    }


    public function setStrSpriteName($strSpriteName) {
        $this->strSpriteName = $strSpriteName;
    }

    /**
     * @return mixed
     */
    public function writeHeader() {
        $this->strOutputBuffer .= "\n";
        $this->strOutputBuffer .= <<<CSS

/* CSS generated by phpImageSpriteGenerator, https://github.com/sidler/phpImageSpriteGenerator */
/* Generated on {date('r')} */


CSS;

    }

    /**
     * @param ImageData[] $arrImageData
     *
     * @return mixed
     */
    public function writeToFile(array $arrImageData) {
        foreach($arrImageData as $objOneData) {

            $strClassName = substr($objOneData->getImageName(), 0, -4);

            $this->strOutputBuffer .= <<<CSS

            .{$strClassName} {
                background-position: {$objOneData->getIntSpriteX()}px {$objOneData->getIntSpriteY()}px;
                background-image: url('sprite.png');
            }
CSS;

        }
    }

    /**
     * @return mixed
     */
    public function writeFooter() {
        $this->strOutputBuffer .= "\n\n";
        file_put_contents($this->strOutputDir.DIRECTORY_SEPARATOR.$this->strOutName, $this->strOutputBuffer);
    }

}