<?php
/**
 * Created by JetBrains PhpStorm.
 * User: sidler
 * Date: 12.08.13
 * Time: 09:33
 * To change this template use File | Settings | File Templates.
 */

class RetinaCssMapper implements IDataMapper {

    private $strOutputBuffer = "";

    /**
     * @return mixed
     */
    public function writeHeader() {
        $this->strOutputBuffer .= "\n";
        $strDate = date('r');
        $this->strOutputBuffer .= <<<CSS

/* CSS generated by phpImageSpriteGenerator, https://github.com/sidler/phpImageSpriteGenerator */
/* This CSS file uses the full-res images (no downscaling) for all images. Downscaling is done by the browser.
/* Generated on {$strDate} */


CSS;

    }

    /**
     * @param ImageData[] $arrImageData
     *
     * @return mixed
     */
    public function writeToFile(array $arrImageData) {
        $strSpriteHighResName = SpriteGenerator::$CONFIG_SPRITE_PREFIX.SpriteGenerator::$CONFIG_SPRITE_FULLRES_NAME.".png";

        $intBackWidth = SpriteGenerator::$SPRITE_TOTAL_WIDTH;
        $intBackHeight = SpriteGenerator::$SPRITE_TOTAL_HEIGHT;

        $intBackFullWidth = floor($intBackWidth/2);
        $intBackFullHeight = floor($intBackHeight/2);

        foreach($arrImageData as $objOneData) {

            $strClassName = substr($objOneData->getImageName(), 0, -4);

            $intFullX = floor($objOneData->getIntSpriteX() / 2);
            $intFullY = floor($objOneData->getIntSpriteY() / 2);


            $this->strOutputBuffer .= <<<CSS

.{$strClassName} {
    background: url('{$strSpriteHighResName}') no-repeat {$intFullX}px -{$intFullY}px;
    background-size:  {$intBackFullWidth}px {$intBackFullHeight}px;
}

CSS;

        }
    }

    /**
     * @return mixed
     */
    public function writeFooter() {
        $this->strOutputBuffer .= "\n\n";
        file_put_contents(SpriteGenerator::$CONFIG_SPRITEGEN_OUTPATH.DIRECTORY_SEPARATOR."combined_fullres.css", $this->strOutputBuffer);
    }

}